base_url = "https://groovyghost.in/"
title = "Groovy Ghost"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true #(e.g.: :smile: => 😄)
[extra]
author = "Ghost"